# Generated by Django 4.2.5 on 2023-09-19 15:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asientosGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ejercicio', models.CharField(blank=True, max_length=255, null=True)),
                ('Jurisdiccion', models.CharField(blank=True, max_length=255, null=True)),
                ('JurisdiccionDescripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('EstructuraProgramatica', models.CharField(blank=True, max_length=255, null=True)),
                ('EstructuraProgramaticaDescripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('FuenteFinanciamiento', models.CharField(blank=True, max_length=255, null=True)),
                ('FuenteFinanciamientoDescripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('ObjetodelGasto', models.CharField(max_length=255)),
                ('ObjetodelGastoDescripcion', models.CharField(max_length=255)),
                ('Fecha', models.DateField()),
                ('ComprobanteTipo', models.CharField(max_length=255)),
                ('ComprobanteEjercicio', models.CharField(max_length=255)),
                ('ComprobanteNumero', models.CharField(max_length=255)),
                ('AplicacionTipo', models.CharField(max_length=255)),
                ('AplicacionEjercicio', models.CharField(max_length=255)),
                ('AplicacionNumero', models.CharField(max_length=255)),
                ('Oficina', models.CharField(blank=True, max_length=255, null=True)),
                ('OficinaDescripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('Obra', models.CharField(blank=True, max_length=255, null=True)),
                ('ObraDescripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('Patrimonio', models.CharField(blank=True, max_length=255, null=True)),
                ('PatrimonioDescripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('ProveedorTipo', models.CharField(blank=True, max_length=255, null=True)),
                ('ProveedorNumero', models.CharField(blank=True, max_length=255, null=True)),
                ('RazonSocial', models.CharField(blank=True, max_length=255, null=True)),
                ('Presupuesto', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Preventivo', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Compromiso', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Devengado', models.DecimalField(decimal_places=2, max_digits=30)),
                ('MandadoaPagar', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Pagado', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.codigofinanciero')),
            ],
            options={
                'verbose_name': 'Asiento de gasto',
                'verbose_name_plural': 'Asientos Gastos',
            },
        ),
        migrations.CreateModel(
            name='regularizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA', models.DateField()),
                ('IMPORTE', models.DecimalField(decimal_places=2, max_digits=30)),
                ('REGISTRO_PAGADO', models.CharField(blank=True, max_length=120, null=True)),
                ('PROVEEDOR', models.CharField(blank=True, max_length=120, null=True)),
                ('FONDO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.fondo')),
                ('GASTO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contaduria.asientosgastos')),
            ],
            options={
                'verbose_name': 'Regularizacion',
                'verbose_name_plural': 'Regularizaciones',
            },
        ),
        migrations.CreateModel(
            name='proyeccionIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MES', models.CharField(choices=[('1', 'ENERO'), ('2', 'FEBRERO'), ('3', 'MARZO'), ('4', 'ABRIL'), ('5', 'MAYO'), ('6', 'JUNIO'), ('7', 'JULIO'), ('8', 'AGOSTO'), ('9', 'SEPTIEMBRE'), ('10', 'OCTUBRE'), ('11', 'NOVIEMBRE'), ('12', 'DICIEMBRE')], max_length=255)),
                ('EJERCICIO', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=255)),
                ('PERIODO', models.DateField(blank=True, null=True)),
                ('IMPORTE', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('MODIFICADO_POR', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('FECHA_MODIFICACION', models.CharField(blank=True, max_length=120, null=True)),
                ('CLASIFICACION', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.equivalencia')),
                ('RECURSO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='proyeccionGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO', models.CharField(blank=True, max_length=120, null=True)),
                ('MES', models.CharField(choices=[('1', 'ENERO'), ('2', 'FEBRERO'), ('3', 'MARZO'), ('4', 'ABRIL'), ('5', 'MAYO'), ('6', 'JUNIO'), ('7', 'JULIO'), ('8', 'AGOSTO'), ('9', 'SEPTIEMBRE'), ('10', 'OCTUBRE'), ('11', 'NOVIEMBRE'), ('12', 'DICIEMBRE')], max_length=255)),
                ('EJERCICIO', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=255)),
                ('PERIODO', models.DateField(blank=True, null=True)),
                ('IMPORTE', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('MODIFICADO_POR', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('FECHA_MODIFICACION', models.CharField(blank=True, max_length=120, null=True)),
                ('CONCEPTO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.concepto')),
                ('PROVEEDOR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA', models.DateField()),
                ('IMPORTE', models.DecimalField(decimal_places=2, max_digits=30)),
                ('PENDIENTE', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('ORDEN_DE_PAGO', models.CharField(blank=True, max_length=120, null=True)),
                ('REGISTRO_PAGADO', models.CharField(blank=True, max_length=120, null=True)),
                ('PROVEEDOR', models.CharField(blank=True, max_length=120, null=True)),
                ('FONDO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.fondo')),
                ('GASTO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contaduria.asientosgastos')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
            },
        ),
        migrations.CreateModel(
            name='devolucionPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ESTADO', models.BooleanField(default=0)),
                ('FECHA', models.DateField(default=django.utils.timezone.now)),
                ('IMPORTE', models.DecimalField(decimal_places=2, max_digits=30)),
                ('FONDO', models.CharField(blank=True, max_length=120, null=True)),
                ('ORDEN_DE_PAGO', models.CharField(blank=True, max_length=120, null=True)),
                ('REGISTRO_PAGADO', models.CharField(blank=True, max_length=120, null=True)),
                ('PROVEEDOR', models.CharField(blank=True, max_length=120, null=True)),
                ('PRESTAMO', models.ForeignKey(limit_choices_to={'PENDIENTE__lt': 0}, on_delete=django.db.models.deletion.PROTECT, to='contaduria.prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='asientosIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ejercicio', models.CharField(blank=True, max_length=255, null=True)),
                ('Recurso_Agrupamiento', models.CharField(blank=True, max_length=255, null=True)),
                ('Recurso_Descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('OrigProc_Agrupamiento', models.CharField(blank=True, max_length=255, null=True)),
                ('OrigProc_Descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('Fecha', models.DateField()),
                ('Devengado', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Percibido', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Clasificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.equivalencia')),
            ],
            options={
                'verbose_name': 'Asiento de ingreso',
                'verbose_name_plural': 'Asientos Ingresos',
            },
        ),
    ]
