# Generated by Django 4.2.5 on 2023-10-02 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0002_desarrollador'),
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA', models.DateTimeField(auto_now_add=True, null=True)),
                ('TITULO', models.CharField(max_length=50)),
                ('DETALLE', models.TextField(blank=True, null=True)),
                ('ESTADO', models.BooleanField(default=0)),
                ('DESARROLLADOR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.desarrollador')),
                ('USUARIO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
