# Generated by Django 4.2.5 on 2023-10-04 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0002_desarrollador'),
        ('solicitud', '0002_mesa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={'verbose_name': 'Solicitud a mesa de ayuda', 'verbose_name_plural': 'Mesa de ayuda'},
        ),
        migrations.AlterField(
            model_name='mesa',
            name='DESARROLLADOR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.desarrollador', verbose_name='Desarrollador asignado'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='DETALLE',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle prolongado (Opcional)'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='ESTADO',
            field=models.BooleanField(default=0, verbose_name='Completado'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='TITULO',
            field=models.CharField(max_length=50, verbose_name='Descripcion corta'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='USUARIO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitante'),
        ),
    ]
