# Generated by Django 4.2.5 on 2023-09-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_contribuyentes',
            name='ALICUOTA_UTILIZADA',
        ),
    ]
