# Generated by Django 4.2.5 on 2023-09-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codigoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO', models.CharField(max_length=20, unique=True)),
                ('NOMBRE', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Codigo',
                'verbose_name_plural': 'Codigos financieros',
            },
        ),
        migrations.CreateModel(
            name='concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
            },
        ),
        migrations.CreateModel(
            name='Equivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrigenProgramatica', models.CharField(max_length=255)),
                ('Descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Equivalencia',
                'verbose_name_plural': 'Equivalencias',
            },
        ),
        migrations.CreateModel(
            name='fondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO', models.CharField(max_length=20, unique=True)),
                ('NOMBRE', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Fondo',
                'verbose_name_plural': 'Fondos',
            },
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ESTADO', models.BooleanField(default=0)),
                ('CODIGO', models.CharField(max_length=50)),
                ('TIPO', models.CharField(blank=True, max_length=50, null=True)),
                ('RAZON_SOCIAL', models.CharField(blank=True, max_length=255, null=True)),
                ('DOMICILIO', models.CharField(blank=True, max_length=255, null=True)),
                ('FECHA_INSCRIPCION', models.DateField(blank=True, null=True)),
                ('CUIT', models.CharField(blank=True, max_length=255, null=True)),
                ('RAMO', models.CharField(blank=True, max_length=255, null=True)),
                ('COMENTARIO', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO', models.CharField(max_length=50, unique=True, verbose_name='Agrupamiento')),
                ('NOMBRE', models.CharField(max_length=2550, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
    ]
