# Generated by Django 4.2.5 on 2023-10-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='desarrollador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LEGAJO', models.CharField(max_length=20, unique=True)),
                ('NOMBRE', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Desarrollador',
                'verbose_name_plural': 'Desarrolladores',
            },
        ),
    ]
